# Generated by Django 3.1.7 on 2021-03-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carta',
            options={'ordering': ['id'], 'verbose_name': 'plato', 'verbose_name_plural': 'platos'},
        ),
        migrations.AddField(
            model_name='category',
            name='condition',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activo'),
        ),
    ]
