# Generated by Django 3.1.7 on 2021-03-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20210311_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle'),
        ),
    ]
