# Generated by Django 3.1.7 on 2021-03-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menudiario', '0003_auto_20210308_0215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acompanamiento',
        ),
    ]
