# Generated by Django 3.1.7 on 2021-03-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menudiario', '0005_acompanamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('condition', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'especial',
                'verbose_name_plural': 'especialidades',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='menudiario',
            options={'ordering': ['id'], 'verbose_name': 'fondo', 'verbose_name_plural': 'fondos'},
        ),
        migrations.AlterField(
            model_name='acompanamiento',
            name='condition',
            field=models.BooleanField(verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='condition',
            field=models.BooleanField(verbose_name='Activo'),
        ),
    ]
