# Generated by Django 3.1.7 on 2021-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menudiario', '0006_auto_20210309_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidades',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
